VirtoCommerce/vc-theme-b2b

- assets/js/account/account-company-members.js
- assets/js/account/account-company-members.tpl.liquid
- assets/js/common-components/errors.tpl.html.liquid
- locales/en.default.json
Add methods and template changes to fire alert for successful user addings in employer account
> VIR-7__successful-user-adding-message

- assets/js/account/account-company-members.js
remove conditional passing or errors array
> errors displaying fixed

- assets/js/account/account-company-members.js
User activating/deactivating message
> Vir 11  member activating message

- assets/js/account/account-company-member-detail.js
- assets/js/account/account-company-member-detail.tpl.liquid
Firing an alert when user is updated
> VIR-10 user update message

- assets/js/account/account-company-members.tpl.liquid
- assets/js/common-components/labeled-input.js
- assets/js/common-components/labeled-input.tpl.html.liquid
- assets/js/common-components/memberDetail.js
- assets/js/common-components/memberDetail.tpl.html.liquid
- assets/js/directives/directives.js
> Grotem account form validation

- assets/js/directives/directives.js
> validation for form company members(update)

- assets/js/account/account-company-members.js
- assets/js/account/account-company-members.tpl.liquid
Isolated alerts for two blocks - newUser & editUser
> isolated alerts fix

- assets/js/common-components/memberDetail.tpl.html.liquid
adding messages for required select role
> Grotem add member select fix

- assets/js/account/account-company-member-detail.js
- assets/js/account/account-company-members.js
- assets/js/directives/directives.js
> Grotem formatting fild budget

- assets/js/collection.js
> fix wrong value for sorting options,comment best-selling option since it's not working correctly for now

- templates/bulk-order.liquid
fix for https://github.com/VirtoCommerce/vc-theme-default/issues/103
> fix error message in "bulk order"

- assets/js/checkout/checkout.js
- assets/js/services.js
- templates/cart.liquid
Nothing happened after click on Update All button.
Added implementation with new API to update the quantity for multiple line-items.
> VP-1219 update all button

- assets/js/account/account.js
- assets/js/checkout/checkout.js
Steps: 
1. Add product to cart
2. Open cart page
3. Click on Clear all button
Nothing happened. 
Expected result: The system clears the cart and shows a message: 'Your cart is now empty'.
> VP-1224 Fix Clear all button in the cart

- templates/customers/account.liquid
> VP-4060: Hide Corporate section from ordinary users

- assets/js/account/account-profile-update.tpl.liquid
- assets/scss/custom/_forms.scss
- assets/scss/custom/_navs.scss
- assets/scss/custom/_type.scss
- locales/en.default.json
- snippets/main/header/top.liquid
- templates/customers/account.liquid
According to new requirements and new page layout
> VP-4048: Implement profile page improvements

- assets/js/account/account-company-member-detail.tpl.liquid
- assets/js/account/account-company-members.js
- assets/js/account/account-company-members.tpl.liquid
- assets/js/account/account-profile-update.js
- assets/js/app/consts.js.liquid
- assets/js/common-components/memberDetail.js
- assets/js/common-components/memberDetail.tpl.html.liquid
- assets/scss/_custom.scss
- assets/scss/_variables.scss
- assets/scss/custom/_tables.scss
- assets/scss/custom/_type.scss
- locales/en.default.json
* Templates for creating/editing users were changed based on new requirements
* Only B2B roles are showing right now
* Partly changed company members page based on new design
(You can see some localization issues in pictures because that parts were related to another task and they are in another PR right now)
> VP-3930: Add a 'Purchasing Agent' role to the list of roles to Profile section on B2B

- assets/js/account/account-orders.js
- assets/js/account/account-orders.tpl.liquid
- assets/js/app/consts.js.liquid
- locales/en.default.json
> VP-3944: Filter orders by status on Order history page

- assets/js/account/account-addresses.js
- assets/js/account/account-addresses.tpl.liquid
- assets/scss/_variables.scss
- assets/scss/custom/_buttons.scss
- assets/scss/custom/_scaffolding.scss
> VP-4269: Redesign addresses page

- assets/js/account/account-orders.js
- assets/js/account/account-orders.tpl.liquid
- assets/js/common-components/lineItems.tpl.liquid
- assets/js/common-components/totals.tpl.liquid
- assets/js/services.js
- assets/scss/_variables.scss
- assets/scss/custom/_panels.scss
- assets/scss/custom/_type.scss
- locales/en.default.json
- templates/thanks.liquid
> VP-3949: Add 'Pay invoice' functionality to order details page

- assets/js/account/account-orders.js
- assets/js/main.js
- assets/scss/_variables.scss
- assets/scss/modules/_vc-alert.scss
- snippets/notification.liquid
> VP-3949: Add notification message after payment is done

- assets/js/account/account-orders.tpl.liquid
for PR: https://github.com/VirtoCommerce/vc-storefront/pull/537
> VP-3949: Fix variable name after storefront changes

- snippets/shared/newsletter-form.liquid
The behavior is now the same as in Electronics theme
> VP-4529: Fix action link for newsletter-form

- assets/js/controllers/dialogs/send-cart-to-email.js
> VP-3977: Close popup on send,show notification,display users to all org

- templates/cart.liquid
> VP-4571: Show price for shipping
